#include "SensorInfo.h"
#include "SensorData.h"
#include "TestSensors.h"
#include "gtest/gtest.h"
#include "BinaryBuffer.h"
#include "boost_endian_arithmetic.hpp"
#include "Packets/PacketInstructions.h"
#include <cmath>
#include <iostream>
#include <string>

using namespace cmbtl;
using namespace cmbtl::test;

// DISCLAIMER: These unit tests were generated by AI but reviewed and modified by a human.

// ================================================================================================
// Tests for encodeSensorData and decodeSensorData
// ================================================================================================

// Test TimeStamp sensor (32-bit unsigned integer)
TEST(SensorDataTests, EncodeDecodeTimeStamp) {
    TestSensorDataType sensorData;

    // Set test value
    boost::endian::big_uint32_t testValue = 1234567890;
    sensorData.setData<TIMESTAMP>(testValue);

    // Encode
    BinaryBuffer buffer(32);
    sensorData.encodeSensorData<TIMESTAMP>(buffer);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    decodedSensorData.decodeSensorData<TIMESTAMP>(buffer);

    // Verify
    ASSERT_EQ(decodedSensorData.getData<TIMESTAMP>(), testValue);
}

// Test Temperature sensor (20-bit unsigned float)
TEST(SensorDataTests, EncodeDecodeTemperature) {
    TestSensorDataType sensorData;

    // Set test value (temperature in degrees)
    float testValue = 85.75f;
    sensorData.setData<TEMPERATURE>(testValue);

    // Encode
    BinaryBuffer buffer(20);
    sensorData.encodeSensorData<TEMPERATURE>(buffer);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    decodedSensorData.decodeSensorData<TEMPERATURE>(buffer);

    // Verify (with precision tolerance for 6 decimal bits)
    float precision = 1.0f / std::pow(2, 6);
    ASSERT_NEAR(decodedSensorData.getData<TEMPERATURE>(), testValue, precision);
}

// Test Pressure sensor (21-bit signed float)
TEST(SensorDataTests, EncodeDecodePressurePositive) {
    TestSensorDataType sensorData;

    // Set test value (positive pressure)
    float testValue = 45.5f;
    sensorData.setData<PRESSURE>(testValue);

    // Encode
    BinaryBuffer buffer(21);
    sensorData.encodeSensorData<PRESSURE>(buffer);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    decodedSensorData.decodeSensorData<PRESSURE>(buffer);

    // Verify (with precision tolerance for 6 decimal bits)
    float precision = 1.0f / std::pow(2, 6);
    ASSERT_NEAR(decodedSensorData.getData<PRESSURE>(), testValue, precision);
}

// Test Pressure sensor with negative value
TEST(SensorDataTests, EncodeDecodePressureNegative) {
    TestSensorDataType sensorData;

    // Set test value (negative pressure)
    float testValue = -15.25f;
    sensorData.setData<PRESSURE>(testValue);

    // Encode
    BinaryBuffer buffer(21);
    sensorData.encodeSensorData<PRESSURE>(buffer);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    decodedSensorData.decodeSensorData<PRESSURE>(buffer);

    // Verify (with precision tolerance for 6 decimal bits)
    float precision = 1.0f / std::pow(2, 6);
    ASSERT_NEAR(decodedSensorData.getData<PRESSURE>(), testValue, precision);
}

// Test RPM sensor (16-bit unsigned integer)
TEST(SensorDataTests, EncodeDecodeRPM) {
    TestSensorDataType sensorData;

    // Set test value
    boost::endian::big_uint16_t testValue = 5500;
    sensorData.setData<RPM>(testValue);

    // Encode
    BinaryBuffer buffer(16);
    sensorData.encodeSensorData<RPM>(buffer);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    decodedSensorData.decodeSensorData<RPM>(buffer);

    // Verify
    ASSERT_EQ(decodedSensorData.getData<RPM>(), testValue);
}

// Test Voltage sensor (16-bit unsigned float with high precision)
TEST(SensorDataTests, EncodeDecodeVoltage) {
    TestSensorDataType sensorData;

    // Set test value (voltage)
    float testValue = 12.567f;
    sensorData.setData<VOLTAGE>(testValue);

    // Encode
    BinaryBuffer buffer(16);
    sensorData.encodeSensorData<VOLTAGE>(buffer);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    decodedSensorData.decodeSensorData<VOLTAGE>(buffer);

    // Verify (with precision tolerance for 8 decimal bits)
    float precision = 1.0f / std::pow(2, 8);
    ASSERT_NEAR(decodedSensorData.getData<VOLTAGE>(), testValue, precision);
}

// Test Status sensor (1-bit boolean) - True
TEST(SensorDataTests, EncodeDecodeStatusTrue) {
    TestSensorDataType sensorData;

    // Set test value
    bool testValue = true;
    sensorData.setData<STATUS>(testValue);

    // Encode
    BinaryBuffer buffer(1);
    sensorData.encodeSensorData<STATUS>(buffer);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    decodedSensorData.decodeSensorData<STATUS>(buffer);

    // Verify
    ASSERT_EQ(decodedSensorData.getData<STATUS>(), testValue);
}

// Test Status sensor (1-bit boolean) - False
TEST(SensorDataTests, EncodeDecodeStatusFalse) {
    TestSensorDataType sensorData;

    // Set test value
    bool testValue = false;
    sensorData.setData<STATUS>(testValue);

    // Encode
    BinaryBuffer buffer(1);
    sensorData.encodeSensorData<STATUS>(buffer);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    decodedSensorData.decodeSensorData<STATUS>(buffer);

    // Verify
    ASSERT_EQ(decodedSensorData.getData<STATUS>(), testValue);
}

// ================================================================================================
// Tests for encodePacket and decodePacket
// ================================================================================================

// Test AllSensors packet (all 6 sensors)
TEST(SensorDataTests, EncodeDecodeAllSensorsPacket) {
    TestSensorDataType sensorData;

    // Set test values for all sensors
    sensorData.setData<TIMESTAMP>(1234567890);
    sensorData.setData<TEMPERATURE>(75.5f);
    sensorData.setData<PRESSURE>(-10.25f);
    sensorData.setData<RPM>(3500);
    sensorData.setData<VOLTAGE>(13.8f);
    sensorData.setData<STATUS>(true);

    // Create packet instructions
    AllSensorsPacket packet = createAllSensorsPacket();

    // Encode packet
    BinaryBuffer buffer = sensorData.encodePacket(packet);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    bool decodeSuccess = decodedSensorData.decodePacket(packet, buffer);

    // Verify decode succeeded
    ASSERT_TRUE(decodeSuccess);

    // Verify all sensor values
    ASSERT_EQ(decodedSensorData.getData<TIMESTAMP>(), sensorData.getData<TIMESTAMP>());

    float tempPrecision = 1.0f / std::pow(2, 6);
    ASSERT_NEAR(decodedSensorData.getData<TEMPERATURE>(), sensorData.getData<TEMPERATURE>(), tempPrecision);

    float presPrecision = 1.0f / std::pow(2, 6);
    ASSERT_NEAR(decodedSensorData.getData<PRESSURE>(), sensorData.getData<PRESSURE>(), presPrecision);

    ASSERT_EQ(decodedSensorData.getData<RPM>(), sensorData.getData<RPM>());

    float voltPrecision = 1.0f / std::pow(2, 8);
    ASSERT_NEAR(decodedSensorData.getData<VOLTAGE>(), sensorData.getData<VOLTAGE>(), voltPrecision);

    ASSERT_EQ(decodedSensorData.getData<STATUS>(), sensorData.getData<STATUS>());
}

// Test CriticalData packet (timestamp, temperature, pressure, rpm)
TEST(SensorDataTests, EncodeDecodeCriticalDataPacket) {
    TestSensorDataType sensorData;

    // Set test values for critical sensors
    sensorData.setData<TIMESTAMP>(5251235);
    sensorData.setData<TEMPERATURE>(105.25f);
    sensorData.setData<PRESSURE>(20.5f);
    sensorData.setData<RPM>(7200);

    // Create packet instructions
    CriticalDataPacket packet = createCriticalDataPacket();

    // Encode packet
    BinaryBuffer buffer = sensorData.encodePacket(packet);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    bool decodeSuccess = decodedSensorData.decodePacket(packet, buffer);

    // Verify decode succeeded
    ASSERT_TRUE(decodeSuccess);

    // Verify critical sensor values
    ASSERT_EQ(decodedSensorData.getData<TIMESTAMP>(), sensorData.getData<TIMESTAMP>());

    float tempPrecision = 1.0f / std::pow(2, 6);
    ASSERT_NEAR(decodedSensorData.getData<TEMPERATURE>(), sensorData.getData<TEMPERATURE>(), tempPrecision);

    float presPrecision = 1.0f / std::pow(2, 6);
    ASSERT_NEAR(decodedSensorData.getData<PRESSURE>(), sensorData.getData<PRESSURE>(), presPrecision);

    ASSERT_EQ(decodedSensorData.getData<RPM>(), sensorData.getData<RPM>());
}

// Test DiagnosticData packet (voltage, status)
TEST(SensorDataTests, EncodeDecodeDiagnosticDataPacket) {
    TestSensorDataType sensorData;

    // Set test values for diagnostic sensors
    sensorData.setData<VOLTAGE>(5.123f);
    sensorData.setData<STATUS>(false);

    // Create packet instructions
    DiagnosticDataPacket packet = createDiagnosticDataPacket();

    // Encode packet
    BinaryBuffer buffer = sensorData.encodePacket(packet);

    // Reset read cursor
    buffer.resetReadCursorPos();

    // Create new sensor data and decode
    TestSensorDataType decodedSensorData;
    bool decodeSuccess = decodedSensorData.decodePacket(packet, buffer);

    // Verify decode succeeded
    ASSERT_TRUE(decodeSuccess);

    // Verify diagnostic sensor values
    float voltPrecision = 1.0f / std::pow(2, 8);
    ASSERT_NEAR(decodedSensorData.getData<VOLTAGE>(), sensorData.getData<VOLTAGE>(), voltPrecision);

    ASSERT_EQ(decodedSensorData.getData<STATUS>(), sensorData.getData<STATUS>());
}

// ================================================================================================
// Tests for serializeDataToJSON
// ================================================================================================

// Test JSON serialization of all sensor data
TEST(SensorDataTests, SerializeDataToJSON) {
    TestSensorDataType sensorData;

    // Set test values for all sensors
    sensorData.setData<TIMESTAMP>(1234567890);
    sensorData.setData<TEMPERATURE>(75.5f);
    sensorData.setData<PRESSURE>(-10.25f);
    sensorData.setData<RPM>(3500);
    sensorData.setData<VOLTAGE>(13.8f);
    sensorData.setData<STATUS>(true);

    // Serialize to JSON
    std::string json = sensorData.serializeDataToJSON();

    // Verify JSON contains sensor names (basic check)
    ASSERT_NE(json.find("timestamp"), std::string::npos);
    ASSERT_NE(json.find("temperature"), std::string::npos);
    ASSERT_NE(json.find("pressure"), std::string::npos);
    ASSERT_NE(json.find("rpm"), std::string::npos);
    ASSERT_NE(json.find("voltage"), std::string::npos);
    ASSERT_NE(json.find("status"), std::string::npos);

    // Verify JSON structure (should start with { and end with })
    ASSERT_EQ(json.front(), '{');
    ASSERT_EQ(json.back(), '}');

    // Output for manual inspection (optional)
    std::cout << "Full JSON:\n" << json << std::endl;
}

// ================================================================================================
// Tests for serializeDataToJSONPacket
// ================================================================================================

// Test JSON serialization of AllSensors packet
TEST(SensorDataTests, SerializeAllSensorsPacketToJSON) {
    TestSensorDataType sensorData;

    // Set test values for all sensors
    sensorData.setData<TIMESTAMP>(1234567890);
    sensorData.setData<TEMPERATURE>(75.5f);
    sensorData.setData<PRESSURE>(-10.25f);
    sensorData.setData<RPM>(3500);
    sensorData.setData<VOLTAGE>(13.8f);
    sensorData.setData<STATUS>(true);

    // Create packet instructions
    AllSensorsPacket packet = createAllSensorsPacket();

    // Serialize to JSON
    std::string json = sensorData.serializeDataToJSONPacket(packet);

    // Verify JSON contains all sensor names
    ASSERT_NE(json.find("timestamp"), std::string::npos);
    ASSERT_NE(json.find("temperature"), std::string::npos);
    ASSERT_NE(json.find("pressure"), std::string::npos);
    ASSERT_NE(json.find("rpm"), std::string::npos);
    ASSERT_NE(json.find("voltage"), std::string::npos);
    ASSERT_NE(json.find("status"), std::string::npos);

    // Verify JSON structure
    ASSERT_EQ(json.front(), '{');
    ASSERT_EQ(json.back(), '}');

    // Output for manual inspection (optional)
    std::cout << "AllSensors JSON:\n" << json << std::endl;
}

// Test JSON serialization of CriticalData packet
TEST(SensorDataTests, SerializeCriticalDataPacketToJSON) {
    TestSensorDataType sensorData;

    // Set test values for all sensors
    sensorData.setData<TIMESTAMP>(1234567890);
    sensorData.setData<TEMPERATURE>(75.5f);
    sensorData.setData<PRESSURE>(-10.25f);
    sensorData.setData<RPM>(3500);
    sensorData.setData<VOLTAGE>(13.8f);
    sensorData.setData<STATUS>(true);

    // Create packet instructions
    CriticalDataPacket packet = createCriticalDataPacket();

    // Serialize to JSON
    std::string json = sensorData.serializeDataToJSONPacket(packet);

    // Verify JSON contains only critical sensor names
    ASSERT_NE(json.find("timestamp"), std::string::npos);
    ASSERT_NE(json.find("temperature"), std::string::npos);
    ASSERT_NE(json.find("pressure"), std::string::npos);
    ASSERT_NE(json.find("rpm"), std::string::npos);

    // Verify JSON does NOT contain diagnostic sensor names
    ASSERT_EQ(json.find("voltage"), std::string::npos);
    ASSERT_EQ(json.find("status"), std::string::npos);

    // Verify JSON structure
    ASSERT_EQ(json.front(), '{');
    ASSERT_EQ(json.back(), '}');

    // Output for manual inspection (optional)
    std::cout << "CriticalData JSON:\n" << json << std::endl;
}

// Test JSON serialization of DiagnosticData packet
TEST(SensorDataTests, SerializeDiagnosticDataPacketToJSON) {
    TestSensorDataType sensorData;

    // Set test values for all sensors
    sensorData.setData<TIMESTAMP>(1234567890);
    sensorData.setData<TEMPERATURE>(75.5f);
    sensorData.setData<PRESSURE>(-10.25f);
    sensorData.setData<RPM>(3500);
    sensorData.setData<VOLTAGE>(13.8f);
    sensorData.setData<STATUS>(true);

    // Create packet instructions
    DiagnosticDataPacket packet = createDiagnosticDataPacket();

    // Serialize to JSON
    std::string json = sensorData.serializeDataToJSONPacket(packet);

    // Verify JSON contains only diagnostic sensor names
    ASSERT_NE(json.find("voltage"), std::string::npos);
    ASSERT_NE(json.find("status"), std::string::npos);

    // Verify JSON does NOT contain critical sensor names
    ASSERT_EQ(json.find("timestamp"), std::string::npos);
    ASSERT_EQ(json.find("temperature"), std::string::npos);
    ASSERT_EQ(json.find("pressure"), std::string::npos);
    ASSERT_EQ(json.find("rpm"), std::string::npos);

    // Verify JSON structure
    ASSERT_EQ(json.front(), '{');
    ASSERT_EQ(json.back(), '}');

    // Output for manual inspection (optional)
    std::cout << "DiagnosticData JSON:\n" << json << std::endl;
}
